spring:
  application:
    name: videolocadora
  datasource:
    url: jdbc:postgresql://localhost:5432/locadora
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      show-sql: true
#      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect